// HandshakeSession.swift — Veu Protocol: Handshake Session Orchestrator
//
// High-level coordinator for the Emerald Handshake ceremony.  Manages the
// state machine, ephemeral key lifecycle, Dead Link generation/consumption,
// and SAS verification flow.

import Foundation
#if canImport(CryptoKit)
import CryptoKit
#else
import Crypto
#endif
import VeuCrypto

/// Orchestrates a single Emerald Handshake session from initiation through
/// confirmation (or failure).
///
/// A `HandshakeSession` tracks one handshake attempt between two peers.  It
/// manages ephemeral key material, enforces the state machine, and provides
/// the derived Circle key and short code upon successful verification.
///
/// # Production Note
/// In a real deployment the signing key would be the device's long-term
/// identity key stored in the Secure Enclave.  For the POC, an in-memory
/// Ed25519 key is used.
public final class HandshakeSession {

    // MARK: - Properties

    /// Current phase of this handshake session.
    public private(set) var phase: HandshakePhase = .idle

    /// The Dead Link generated by the initiating peer (nil for responder).
    public private(set) var deadLink: DeadLink?

    /// The 8-digit short code (available after phase transitions to `.verifying`).
    public private(set) var shortCode: String?

    /// The Aura color hex (available after phase transitions to `.verifying`).
    public private(set) var auraColorHex: String?

    /// The derived Circle key (available after `.confirmed`).
    public private(set) var circleKey: CircleKey?

    /// The Circle identifier assigned to this handshake.
    public let circleID: String

    // MARK: - Private State

    private var localKeypair: EphemeralKeypair?
    private var signingKey: Curve25519.Signing.PrivateKey?
    private var remotePublicKey: Curve25519.KeyAgreement.PublicKey?
    private let createdAt: Date
    private let timeout: TimeInterval
    
    /// The peer's X25519 public key data (available after verifying phase).
    public var peerPublicKeyData: Data? {
        remotePublicKey?.rawRepresentation
    }

    // MARK: - Init

    /// Create a new handshake session.
    ///
    /// - Parameters:
    ///   - circleID: Identifier for the Circle being established (default: random UUID).
    ///   - timeout: Session timeout in seconds (default: 10 minutes).
    public init(circleID: String = UUID().uuidString, timeout: TimeInterval = 600) {
        self.circleID = circleID
        self.timeout = timeout
        self.createdAt = Date()
    }

    // MARK: - Initiator Flow

    /// **Initiator Step 1:** Generate an ephemeral keypair and Dead Link.
    ///
    /// Transitions: `IDLE` → `INITIATING`
    ///
    /// - Parameter ttl: Dead Link time-to-live (default: 5 minutes).
    /// - Throws: `VeuAuthError.invalidStateTransition` if not in `.idle`.
    /// - Returns: The generated `DeadLink` (encode via `.toURI()` for QR display).
    @discardableResult
    public func initiate(ttl: TimeInterval = DeadLink.defaultTTL) throws -> DeadLink {
        guard phase == .idle else {
            throw VeuAuthError.invalidStateTransition
        }

        let keypair = EphemeralKeypair.generate()
        let signing = Curve25519.Signing.PrivateKey()

        let link = try DeadLink.generate(
            keyAgreementPublicKey: keypair.publicKey,
            signingKey: signing,
            ttl: ttl
        )

        self.localKeypair = keypair
        self.signingKey = signing
        self.deadLink = link
        self.phase = .initiating

        return link
    }

    /// **Initiator Step 2:** Receive the responder's public key and compute the shared secret.
    ///
    /// Transitions: `INITIATING` → `VERIFYING`
    ///
    /// - Parameter remotePublicKeyData: The responder's raw X25519 public key (32 bytes).
    /// - Throws: `VeuAuthError.invalidStateTransition`, `.keyAgreementFailed`,
    ///           `.keyDerivationFailed`, or `.sessionTimeout`.
    public func receiveResponse(remotePublicKeyData: Data) throws {
        guard phase == .initiating else {
            throw VeuAuthError.invalidStateTransition
        }
        try checkTimeout()

        guard let remotePK = try? Curve25519.KeyAgreement.PublicKey(rawRepresentation: remotePublicKeyData) else {
            throw VeuAuthError.keyAgreementFailed
        }

        self.remotePublicKey = remotePK
        try deriveAndTransitionToVerifying()
    }

    // MARK: - Responder Flow

    /// **Responder Step 1:** Parse a Dead Link, generate a local keypair, and compute the shared secret.
    ///
    /// Transitions: `IDLE` → `VERIFYING`
    ///
    /// This combines several steps for the responder: parse the link,
    /// generate an ephemeral keypair, perform ECDH, and derive the short code.
    ///
    /// - Parameter uri: The Dead Link URI string scanned from QR or received via link.
    /// - Throws: `VeuAuthError.deadLinkInvalid`, `.deadLinkExpired`,
    ///           `.keyAgreementFailed`, or `.keyDerivationFailed`.
    /// - Returns: The local X25519 public key data to send back to the initiator.
    @discardableResult
    public func respond(to uri: String) throws -> Data {
        guard phase == .idle else {
            throw VeuAuthError.invalidStateTransition
        }

        let link = try DeadLink.parse(uri: uri)

        guard !link.isExpired() else {
            throw VeuAuthError.deadLinkExpired
        }

        let keypair = EphemeralKeypair.generate()
        self.localKeypair = keypair
        self.deadLink = link
        self.remotePublicKey = link.publicKey
        // Transition through awaiting to verifying
        self.phase = .awaiting

        try deriveAndTransitionToVerifying()

        return keypair.publicKey.rawRepresentation
    }

    /// **Responder Step 1 (Direct):** Accept a raw remote public key and local keypair directly,
    /// bypassing Dead Link parsing. Used for proximity handshakes.
    ///
    /// Transitions: `IDLE` → `VERIFYING`
    ///
    /// - Parameters:
    ///   - remotePublicKeyData: The initiator's raw X25519 public key (32 bytes).
    ///   - localKeypair: The pre-generated ephemeral keypair for this responder.
    /// - Throws: `VeuAuthError.keyAgreementFailed` or `.keyDerivationFailed`.
    public func respondDirect(remotePublicKeyData: Data, localKeypair: EphemeralKeypair) throws {
        guard phase == .idle else {
            throw VeuAuthError.invalidStateTransition
        }

        guard let remotePK = try? Curve25519.KeyAgreement.PublicKey(rawRepresentation: remotePublicKeyData) else {
            throw VeuAuthError.keyAgreementFailed
        }

        self.localKeypair = localKeypair
        self.remotePublicKey = remotePK
        self.phase = .awaiting

        try deriveAndTransitionToVerifying()
    }

    // MARK: - Verification

    /// **Both Peers:** Confirm that the displayed short code matches.
    ///
    /// Transitions: `VERIFYING` → `CONFIRMED`
    ///
    /// - Throws: `VeuAuthError.invalidStateTransition` or `.sessionTimeout`.
    public func confirm() throws {
        guard phase == .verifying else {
            throw VeuAuthError.invalidStateTransition
        }
        try checkTimeout()
        self.phase = .confirmed
    }

    /// **Both Peers:** Reject the short code or abort the handshake.
    ///
    /// Transitions: any phase → `GHOST`
    public func reject() {
        self.phase = .ghost
        zeroKeyMaterial()
    }

    /// **Both Peers:** Mark the Dead Link as expired.
    ///
    /// Transitions: `INITIATING` → `DEAD_LINK`
    public func expire() {
        self.phase = .deadLink
        zeroKeyMaterial()
    }

    // MARK: - Snapshot Support

    /// Export the current session state for persistence.
    /// Only meaningful in `.initiating` or `.verifying` phase.
    public func exportSnapshot() -> HandshakeSessionSnapshot? {
        guard phase == .initiating || phase == .verifying else { return nil }
        guard let localKeypair = localKeypair else { return nil }

        return HandshakeSessionSnapshot(
            circleID: circleID,
            phase: phase == .initiating ? "initiating" : "verifying",
            localPrivateKeyData: localKeypair.privateKey.rawRepresentation,
            remotePublicKeyData: remotePublicKey?.rawRepresentation,
            shortCode: shortCode,
            auraColorHex: auraColorHex,
            circleKeyData: circleKey?.keyData,
            glazeSaltData: circleKey?.glazeSalt,
            deadLinkURI: deadLink?.toURI(),
            createdAt: createdAt,
            timeout: timeout
        )
    }

    /// Restore a session from a persisted snapshot.
    /// Returns nil if the snapshot is expired or data is invalid.
    public static func restore(from snapshot: HandshakeSessionSnapshot) -> HandshakeSession? {
        // Check expiry
        if Date().timeIntervalSince(snapshot.createdAt) > snapshot.timeout {
            return nil
        }

        guard let privKey = try? Curve25519.KeyAgreement.PrivateKey(
            rawRepresentation: snapshot.localPrivateKeyData
        ) else { return nil }

        let session = HandshakeSession(circleID: snapshot.circleID, timeout: snapshot.timeout)
        // Manually set internal state (bypass state machine for restoration)
        session.localKeypair = EphemeralKeypair(privateKey: privKey, publicKey: privKey.publicKey)

        if let remotePKData = snapshot.remotePublicKeyData,
           let remotePK = try? Curve25519.KeyAgreement.PublicKey(rawRepresentation: remotePKData) {
            session.remotePublicKey = remotePK
        }

        session.shortCode = snapshot.shortCode
        session.auraColorHex = snapshot.auraColorHex

        if let keyData = snapshot.circleKeyData, let glazeSalt = snapshot.glazeSaltData {
            session.circleKey = CircleKey(keyData: keyData, glazeSalt: glazeSalt)
        }

        switch snapshot.phase {
        case "initiating":
            session.phase = .initiating
        case "verifying":
            session.phase = .verifying
        default:
            return nil
        }

        return session
    }

    // MARK: - Private Helpers

    private func deriveAndTransitionToVerifying() throws {
        guard let localKeypair = localKeypair,
              let remotePK = remotePublicKey else {
            throw VeuAuthError.keyAgreementFailed
        }

        let derivedKey = try EmeraldHandshake.performKeyExchange(
            localPrivateKey: localKeypair.privateKey,
            remotePublicKey: remotePK,
            circleID: circleID
        )

        self.circleKey = derivedKey
        self.shortCode = ShortCode.deriveCode(from: derivedKey)
        self.auraColorHex = ShortCode.deriveAuraColorHex(from: derivedKey)
        self.phase = .verifying
    }

    private func checkTimeout() throws {
        if Date().timeIntervalSince(createdAt) > timeout {
            self.phase = .ghost
            zeroKeyMaterial()
            throw VeuAuthError.sessionTimeout
        }
    }

    private func zeroKeyMaterial() {
        self.localKeypair = nil
        self.signingKey = nil
        self.remotePublicKey = nil
    }
}

// MARK: - Snapshot Model

/// Persistable snapshot of a HandshakeSession's state.
/// Stored device-local (not synced) for recovery after app background/crash.
public struct HandshakeSessionSnapshot: Codable, Sendable {
    public let circleID: String
    public let phase: String
    public let localPrivateKeyData: Data
    public let remotePublicKeyData: Data?
    public let shortCode: String?
    public let auraColorHex: String?
    public let circleKeyData: Data?
    public let glazeSaltData: Data?
    public let deadLinkURI: String?
    public let createdAt: Date
    public let timeout: TimeInterval

    public init(
        circleID: String,
        phase: String,
        localPrivateKeyData: Data,
        remotePublicKeyData: Data? = nil,
        shortCode: String? = nil,
        auraColorHex: String? = nil,
        circleKeyData: Data? = nil,
        glazeSaltData: Data? = nil,
        deadLinkURI: String? = nil,
        createdAt: Date = Date(),
        timeout: TimeInterval = 600
    ) {
        self.circleID = circleID
        self.phase = phase
        self.localPrivateKeyData = localPrivateKeyData
        self.remotePublicKeyData = remotePublicKeyData
        self.shortCode = shortCode
        self.auraColorHex = auraColorHex
        self.circleKeyData = circleKeyData
        self.glazeSaltData = glazeSaltData
        self.deadLinkURI = deadLinkURI
        self.createdAt = createdAt
        self.timeout = timeout
    }

    /// Whether this snapshot has expired.
    public var isExpired: Bool {
        Date().timeIntervalSince(createdAt) > timeout
    }
}
