// HandshakeSession.swift — Veu Protocol: Handshake Session Orchestrator
//
// High-level coordinator for the Emerald Handshake ceremony.  Manages the
// state machine, ephemeral key lifecycle, Dead Link generation/consumption,
// and SAS verification flow.

import Foundation
#if canImport(CryptoKit)
import CryptoKit
#else
import Crypto
#endif
import VeuCrypto

/// Orchestrates a single Emerald Handshake session from initiation through
/// confirmation (or failure).
///
/// A `HandshakeSession` tracks one handshake attempt between two peers.  It
/// manages ephemeral key material, enforces the state machine, and provides
/// the derived Circle key and short code upon successful verification.
///
/// # Production Note
/// In a real deployment the signing key would be the device's long-term
/// identity key stored in the Secure Enclave.  For the POC, an in-memory
/// Ed25519 key is used.
public final class HandshakeSession {

    // MARK: - Properties

    /// Current phase of this handshake session.
    public private(set) var phase: HandshakePhase = .idle

    /// The Dead Link generated by the initiating peer (nil for responder).
    public private(set) var deadLink: DeadLink?

    /// The 8-digit short code (available after phase transitions to `.verifying`).
    public private(set) var shortCode: String?

    /// The Aura color hex (available after phase transitions to `.verifying`).
    public private(set) var auraColorHex: String?

    /// The derived Circle key (available after `.confirmed`).
    public private(set) var circleKey: CircleKey?

    /// The Circle identifier assigned to this handshake.
    public let circleID: String

    // MARK: - Private State

    private var localKeypair: EphemeralKeypair?
    private var signingKey: Curve25519.Signing.PrivateKey?
    private var remotePublicKey: Curve25519.KeyAgreement.PublicKey?
    private let createdAt: Date
    private let timeout: TimeInterval

    // MARK: - Init

    /// Create a new handshake session.
    ///
    /// - Parameters:
    ///   - circleID: Identifier for the Circle being established (default: random UUID).
    ///   - timeout: Session timeout in seconds (default: 10 minutes).
    public init(circleID: String = UUID().uuidString, timeout: TimeInterval = 600) {
        self.circleID = circleID
        self.timeout = timeout
        self.createdAt = Date()
    }

    // MARK: - Initiator Flow

    /// **Initiator Step 1:** Generate an ephemeral keypair and Dead Link.
    ///
    /// Transitions: `IDLE` → `INITIATING`
    ///
    /// - Parameter ttl: Dead Link time-to-live (default: 5 minutes).
    /// - Throws: `VeuAuthError.invalidStateTransition` if not in `.idle`.
    /// - Returns: The generated `DeadLink` (encode via `.toURI()` for QR display).
    @discardableResult
    public func initiate(ttl: TimeInterval = DeadLink.defaultTTL) throws -> DeadLink {
        guard phase == .idle else {
            throw VeuAuthError.invalidStateTransition
        }

        let keypair = EphemeralKeypair.generate()
        let signing = Curve25519.Signing.PrivateKey()

        let link = try DeadLink.generate(
            keyAgreementPublicKey: keypair.publicKey,
            signingKey: signing,
            ttl: ttl
        )

        self.localKeypair = keypair
        self.signingKey = signing
        self.deadLink = link
        self.phase = .initiating

        return link
    }

    /// **Initiator Step 2:** Receive the responder's public key and compute the shared secret.
    ///
    /// Transitions: `INITIATING` → `VERIFYING`
    ///
    /// - Parameter remotePublicKeyData: The responder's raw X25519 public key (32 bytes).
    /// - Throws: `VeuAuthError.invalidStateTransition`, `.keyAgreementFailed`,
    ///           `.keyDerivationFailed`, or `.sessionTimeout`.
    public func receiveResponse(remotePublicKeyData: Data) throws {
        guard phase == .initiating else {
            throw VeuAuthError.invalidStateTransition
        }
        try checkTimeout()

        guard let remotePK = try? Curve25519.KeyAgreement.PublicKey(rawRepresentation: remotePublicKeyData) else {
            throw VeuAuthError.keyAgreementFailed
        }

        self.remotePublicKey = remotePK
        try deriveAndTransitionToVerifying()
    }

    // MARK: - Responder Flow

    /// **Responder Step 1:** Parse a Dead Link, generate a local keypair, and compute the shared secret.
    ///
    /// Transitions: `IDLE` → `VERIFYING`
    ///
    /// This combines several steps for the responder: parse the link,
    /// generate an ephemeral keypair, perform ECDH, and derive the short code.
    ///
    /// - Parameter uri: The Dead Link URI string scanned from QR or received via link.
    /// - Throws: `VeuAuthError.deadLinkInvalid`, `.deadLinkExpired`,
    ///           `.keyAgreementFailed`, or `.keyDerivationFailed`.
    /// - Returns: The local X25519 public key data to send back to the initiator.
    @discardableResult
    public func respond(to uri: String) throws -> Data {
        guard phase == .idle else {
            throw VeuAuthError.invalidStateTransition
        }

        let link = try DeadLink.parse(uri: uri)

        guard !link.isExpired() else {
            throw VeuAuthError.deadLinkExpired
        }

        let keypair = EphemeralKeypair.generate()
        self.localKeypair = keypair
        self.deadLink = link
        self.remotePublicKey = link.publicKey
        // Transition through awaiting to verifying
        self.phase = .awaiting

        try deriveAndTransitionToVerifying()

        return keypair.publicKey.rawRepresentation
    }

    /// **Responder Step 1 (Direct):** Accept a raw remote public key and local keypair directly,
    /// bypassing Dead Link parsing. Used for proximity handshakes.
    ///
    /// Transitions: `IDLE` → `VERIFYING`
    ///
    /// - Parameters:
    ///   - remotePublicKeyData: The initiator's raw X25519 public key (32 bytes).
    ///   - localKeypair: The pre-generated ephemeral keypair for this responder.
    /// - Throws: `VeuAuthError.keyAgreementFailed` or `.keyDerivationFailed`.
    public func respondDirect(remotePublicKeyData: Data, localKeypair: EphemeralKeypair) throws {
        guard phase == .idle else {
            throw VeuAuthError.invalidStateTransition
        }

        guard let remotePK = try? Curve25519.KeyAgreement.PublicKey(rawRepresentation: remotePublicKeyData) else {
            throw VeuAuthError.keyAgreementFailed
        }

        self.localKeypair = localKeypair
        self.remotePublicKey = remotePK
        self.phase = .awaiting

        try deriveAndTransitionToVerifying()
    }

    // MARK: - Verification

    /// **Both Peers:** Confirm that the displayed short code matches.
    ///
    /// Transitions: `VERIFYING` → `CONFIRMED`
    ///
    /// - Throws: `VeuAuthError.invalidStateTransition` or `.sessionTimeout`.
    public func confirm() throws {
        guard phase == .verifying else {
            throw VeuAuthError.invalidStateTransition
        }
        try checkTimeout()
        self.phase = .confirmed
    }

    /// **Both Peers:** Reject the short code or abort the handshake.
    ///
    /// Transitions: any phase → `GHOST`
    public func reject() {
        self.phase = .ghost
        zeroKeyMaterial()
    }

    /// **Both Peers:** Mark the Dead Link as expired.
    ///
    /// Transitions: `INITIATING` → `DEAD_LINK`
    public func expire() {
        self.phase = .deadLink
        zeroKeyMaterial()
    }

    // MARK: - Private Helpers

    private func deriveAndTransitionToVerifying() throws {
        guard let localKeypair = localKeypair,
              let remotePK = remotePublicKey else {
            throw VeuAuthError.keyAgreementFailed
        }

        let derivedKey = try EmeraldHandshake.performKeyExchange(
            localPrivateKey: localKeypair.privateKey,
            remotePublicKey: remotePK,
            circleID: circleID
        )

        self.circleKey = derivedKey
        self.shortCode = ShortCode.deriveCode(from: derivedKey)
        self.auraColorHex = ShortCode.deriveAuraColorHex(from: derivedKey)
        self.phase = .verifying
    }

    private func checkTimeout() throws {
        if Date().timeIntervalSince(createdAt) > timeout {
            self.phase = .ghost
            zeroKeyMaterial()
            throw VeuAuthError.sessionTimeout
        }
    }

    private func zeroKeyMaterial() {
        self.localKeypair = nil
        self.signingKey = nil
        self.remotePublicKey = nil
    }
}
